In [1]:
import pandas as pd
import numpy as np

In [2]:
prices = pd.read_csv('https://seshat.datasd.org/city_owned_properties_leases/city_property_leases_datasd.csv')
prices

,site_code,lessee_name,lessee_company,lessee_DBA,address_zip,lease_record_type,lease_description,lease_status,lease_location_name,nonprofit_lessee,date_effective,date_sched_termination,rent_code,cost_line_amt_USD
0,A001WR,"NEAL, ROBERT","NEAL, ROBERT",NaN,92065,Lease,AGRICULTURE & CATTLE GRAZING,Held Over,PAMO VALLEY,0.0,4/18/2019,4/17/2022,NaN,NaN
1,A001WR,SAN DIEGUITO RIVER PARK JPA/15,SAN DIEGUITO RIVER PARK JPA,NaN,92025,Permit,MAINTENANCE & RESTORATION,Normal,PAMO VALLEY,0.0,12/1/2016,11/30/2036,NaN,NaN
2,A007WW,PACIFIC TELEPHONE/01,PACIFIC TELEPHONE/01,AT&T,75202-4206,Permit,TELEPHONE CABLE,MTM,"SUTHERLAND DAM, CITY RESIDENCE",0.0,3/12/1974,NaN,NaN,NaN
3,ADMIN,"AG ESSENTIAL HOUSING CA 2, LP","AG ESSENTIAL HOUSING CA 2, LP",NaN,92008,Agreement,OTAY 2ND PIPELINE EASEMENT,MTM,"CHULA VISTA, COUNTY OF SAN DIEGO",0.0,11/4/2021,NaN,NaN,NaN
4,ADMIN,"WESTFIELD CORPORATION, INC.",Spinoso Real Estate Group,NORTH COUNTY FAIR,13212,Agreement,SHOPPING CENTER,Normal,I-15& VIA RANCHO PARKWAY ESCONDIDO,0.0,4/8/1980,6/30/2033,FMD,8333.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
809,Z715PM,SD METROPOLITAN TRANSIT SYSTEM,SD METROPOLITAN TRANSIT SYSTEM,NaN,92101-7490,Agreement,COMMUNICATIONS EQUIPMENT,Held Over,MOODY CANYON COM CENTER-SAN YSIDRO,0.0,11/1/2014,10/31/2024,FYR,33866.90
810,Z715PM,STATE OF CA/CHP/03,STATE OF CA/CHP/03,DEPT. OF GENERAL SERVICES-DGS,95798-9052,Lease,COMMUNICATIONS FACILITY,Held Over,MOODY CANYON AKA SAN YSIDRO,0.0,3/1/2012,2/28/2022,FQR,9983.09
811,Z715PM,US CUSTOMS & BORDER PROTECTION/05,US CUSTOMS & BORDER PROTECTION,NaN,76040,Lease,TELECOMMUNICATIONS EQUIPMENT,Normal,SAN YSIDRO/ MOODY CANYON,0.0,10/1/2017,9/30/2037,NaN,NaN
812,Z719PM,COUNTY OF SAN DIEGO/12 TIJUANA RIVER PARK,COUNTY OF SAN DIEGO/12,NaN,92123-1666,Joint Powers,MAINTENANCE OF PARK,Held Over,TIJUANA RIVER REGIONAL PARK,0.0,3/4/1996,3/3/2021,NaN,NaN
813,Z728PM,INTERCAM FINANCIAL SERVICES INC,INTERCAM FINANCIAL SERVICES INC,NaN,92173,Permit,PARKING,Normal,ADJACENT 360-399 E. SAN YSIDRO BLVD. SAN DIEGO...,0.0,12/1/2024,11/30/2029,FMD,4748.00

In [3]:
prices.columns

Index(['site_code', 'lessee_name', 'lessee_company', 'lessee_DBA',
       'address_zip', 'lease_record_type', 'lease_description', 'lease_status',
       'lease_location_name', 'nonprofit_lessee', 'date_effective',
       'date_sched_termination', 'rent_code', 'cost_line_amt_USD'],
      dtype='object')

In [4]:
prices = prices.drop(columns=['lessee_name', 'lessee_company', 'lessee_DBA'])
prices.shape

(814, 11)

In [5]:
prices = prices.dropna(subset=['cost_line_amt_USD'])

In [6]:
prices.shape

(545, 11)

In [7]:
prices

,site_code,address_zip,lease_record_type,lease_description,lease_status,lease_location_name,nonprofit_lessee,date_effective,date_sched_termination,rent_code,cost_line_amt_USD
4,ADMIN,13212,Agreement,SHOPPING CENTER,Normal,I-15& VIA RANCHO PARKWAY ESCONDIDO,0.0,4/8/1980,6/30/2033,FMD,8333.33
5,ADMIN,92101-5522,Lease,TRANSITIONAL HOUSING 5550,Normal,"FRIARS RD, MISSION VALLEY",1.0,5/1/2026,4/30/2036,FMD,402.00
6,BLDG,92103-1946,Lease,CHILD CARE CENTER,MTM,1425 WASHINGTON PL SD CA 92103,0.0,3/1/2002,2/29/2012,FMD,1424.44
8,C601WR,92025-2301,Lease,PEDESTRIAN BRIDGE,Normal,"HODGES RESERVOIR, WEST OF I-15",0.0,11/1/2007,10/31/2032,FYD,525.40
12,C701P2,92110,Permit,OPERATION AND MAINTENANCE OF STATE HISTORICAL ...,Held Over,POR RHO SAN BERNARDO,0.0,4/1/1988,3/31/1993,FYD,100.00
...,...,...,...,...,...,...,...,...,...,...,...
807,Z706RS,NaN,Permit,Expense to Park and Rec paid interfund to Water,MTM,Sycamore Rd - San Ysidro Park,0.0,12/18/1973,NaN,FYD,4100.00
808,Z706RS,92101,Lease,SPORTS FIELD,MTM,"SAN YSIDRO, LARSEN FIELD",0.0,12/18/1973,NaN,FYD,4100.00
809,Z715PM,92101-7490,Agreement,COMMUNICATIONS EQUIPMENT,Held Over,MOODY CANYON COM CENTER-SAN YSIDRO,0.0,11/1/2014,10/31/2024,FYR,33866.90
810,Z715PM,95798-9052,Lease,COMMUNICATIONS FACILITY,Held Over,MOODY CANYON AKA SAN YSIDRO,0.0,3/1/2012,2/28/2022,FQR,9983.09
813,Z728PM,92173,Permit,PARKING,Normal,ADJACENT 360-399 E. SAN YSIDRO BLVD. SAN DIEGO...,0.0,12/1/2024,11/30/2029,FMD,4748.00

In [8]:
prices['date_effective'] = pd.to_datetime(prices['date_effective'])

print(prices['date_effective'].max())
print(prices['date_effective'].min())

2026-05-01 00:00:00
1946-03-26 00:00:00

In [9]:
prices['date_sched_termination'] = pd.to_datetime(prices['date_sched_termination'])

print(prices['date_sched_termination'].max())
print(prices['date_sched_termination'].min())

2077-03-31 00:00:00
1993-03-31 00:00:00

In [10]:
prices[prices['lease_record_type'] == 'House Rental']

,site_code,address_zip,lease_record_type,lease_description,lease_status,lease_location_name,nonprofit_lessee,date_effective,date_sched_termination,rent_code,cost_line_amt_USD
26,C701WW,92027,House Rental,"SINGLE STORY RESIDENCE, SAN PASQUAL VALLEY",MTM,17425 BRANDY CANYON ROAD,0.0,2010-04-01,NaT,FMD,633.34
28,C701WW,92027-7105,House Rental,SINGLE STORY RESIDENCE,MTM,17407 BANDY CANYON RD.,0.0,2013-08-01,NaT,FMD,633.34
36,C701WW,92025,House Rental,RESIDENTIAL,MTM,17178 BANDY CANYON RD,0.0,2011-02-01,NaT,FMD,535.90
37,C701WW,92025,House Rental,RESIDENTIAL,MTM,17082 BANDY CANYON RD,0.0,2011-02-01,NaT,PYR,0.00
38,C701WW,92025,House Rental,RESIDENTIAL,MTM,17078 BANDY CANYON RD,0.0,2011-02-01,NaT,FMD,535.90
39,C701WW,92069,House Rental,RESIDENTIAL,MTM,17070 BANDY CANYON RD,0.0,2016-11-04,NaT,FMD,535.90
40,C701WW,92025-3606,House Rental,HOUSE RENTAL,MTM,16777 BANDY CANYON RD,0.0,2011-06-01,NaT,FMD,2358.00
574,S201RD,92102,House Rental,SINGLE-FAMILY RESIDENCE,MTM,"4101 LOMALAND DR. #1., SD 92107",0.0,1992-12-21,NaT,FMD,1954.68
575,S201RD,92106,House Rental,SINGLE-FAMILY RESIDENCE,MTM,"4101 LOMALAND DR., #3, SD, 92107",0.0,1995-07-17,NaT,FMD,1921.70
576,S201RD,92106,House Rental,SINGLE-FAMILY RESIDENCE,MTM,"4101 LOMALAND DR., #4, SD 92107",0.0,1996-01-04,NaT,FMD,781.87
577,S201RD,92107,House Rental,SINGLE FAMILY RESIDENCE,MTM,"4515 LADERA STREET, S.D. 92107",0.0,1995-08-01,NaT,FMD,2932.05
691,T001WM,91935,House Rental,SINGLE FAMILY RESIDENCE,MTM,"1126 BARRETT LAKE ROAD, SD",0.0,2007-04-14,NaT,FMD,650.00

In [11]:
prices = prices[(prices['date_effective'] >= '2005-01-05') & (prices['date_effective'] <= '2022-11-22')]

In [12]:
prices.shape

(339, 11)